"""pre initial migrations

Revision ID: 425be0562feb
Revises: 
Create Date: 2025-01-15 16:43:12.400971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "425be0562feb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("balance", sa.DECIMAL(scale=2), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_wallets_uuid"), "wallets", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallets_uuid"), table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###
